// Generated by dts-bundle-generator v8.0.0

declare const exportedThing: {
	/**
	 * A thing.
	 */
	importedThing: {
		someFunction(arg1: string, arg2: string): void;
	};
};

export {
	exportedThing as default,
};

export {};
