// Generated by dts-bundle-generator v8.0.0

declare const importedThing: {
	/**
	 * A function that does something.
	 * @param arg1 The first argument.
	 * @param arg2 The second argument.
	 */
	someFunction(arg1: string, arg2: string): void;
};
declare namespace exportedThing {
	export { importedThing };
}

export {
	exportedThing as default,
};

export {};
